export const extensionSettings = {
  //{ id: 'theme-toggle', label: 'Dark Mode', type: 'checkbox', default: false, tag: 'light mode' },
  Platforms: [
    { id: 'facebook-toggle', label: 'Enable Facebook', type: 'checkbox', default: true, tag: 'on/off' },
    { id: 'twitch-toggle', label: 'Enable Twitch', type: 'checkbox', default: true, tag: 'on/off' },
    { id: 'twitter-toggle', label: 'Enable Twitter', type: 'checkbox', default: true, tag: 'on/off' },
    { id: 'youtube-toggle', label: 'Enable Youtube', type: 'checkbox', default: true, tag: 'on/off' },
  ],
  General: [
    {
      id: 'ex-timeout',
      label: 'Setting Timeout (seconds)',
      type: 'number',
      default: 0,
      min: 0,
      max: 300,
      tag: 'timeout',
    },
    { id: 'scroll-limit', label: 'Limit Scrolling', type: 'checkbox', default: true, tag: 'scroll' },
    { id: 'grayscale-toggle', label: 'Grayscale', type: 'checkbox', default: false, tag: 'grayscale' },
    { id: 'navs-toggle', label: 'Disable Navigation', type: 'checkbox', default: false, tag: 'nav' },
    { id: 'imagevideo-toggle', label: 'Hide Images/Videos', type: 'checkbox', default: false, tag: 'image/video' },
  ],
  Posts: [
    { id: 'limit-toggle', label: 'Limit Posts', type: 'checkbox', default: true, tag: 'limit' },
    { id: 'limit-value', label: 'Limit Posts Amount', type: 'number', default: 1100, min: 0, max: 1000, tag: 'limit' },
    { id: 'postings-toggle', label: 'Hide Post Creation Menu', type: 'checkbox', default: true, tag: 'posting' },
  ],
  Content: [
    {
      id: 'content-filter-visibility',
      label: 'Content Filter Visibility',
      type: 'select',
      default: 'min',
      options: [
        { value: 'none', text: 'Off' },
        { value: 'min', text: 'Minimize' },
        { value: 'hide', text: 'Hide' },
      ],
      tag: 'content',
    },
    {
      id: 'filtered-words',
      label: 'Word/Phrase Filter',
      type: 'array',
      default: [],
      placeholder: 'e.g. Breaking Bad',
      tag: 'content',
    },
  ],
  Channels: [
    {
      id: 'channel-filter-visibility',
      label: 'Channel Filter Visibility',
      type: 'select',
      default: 'min',
      options: [
        { value: 'none', text: 'Off' },
        { value: 'min', text: 'Minimize' },
        { value: 'hide', text: 'Hide' },
      ],
      tag: 'content',
    },
    {
      id: 'filtered-channels',
      label: 'Channel Filter',
      type: 'array',
      default: [],
      placeholder: `e.g. Sam O'Nella Academy`,
      tag: 'content',
    },
  ],
  Bias: [
    { id: 'enable-bias', label: 'Enable Bias Classification', type: 'checkbox', default: true, tag: 'ai' },
    {
      id: 'bias-filter-visibility',
      label: 'Bias Filter Visibility',
      type: 'select',
      default: 'min',
      tag: 'bias',
      options: [
        { value: 'min', text: 'Minimize' },
        { value: 'hide', text: 'Hide' },
      ],
    },
    { id: 'bias-threshold', label: 'Threshold', type: 'number', default: 50, min: 5, max: 95, tag: 'bias' },
  ],
  Topic: [
    {
      id: 'enable-topic',
      label: 'Enable Topic Classification',
      type: 'checkbox',
      default: false,
      tag: 'topic', //rename to ai once fixed
    },
    {
      id: 'topic-filter-visibility',
      label: 'Topic Filter Visibility',
      type: 'select',
      default: 'min',
      options: [
        { value: 'min', text: 'Minimize' },
        { value: 'hide', text: 'Hide' },
      ],
      tag: 'topic',
    },
    { id: 'enable-tech', label: 'Hide Tech', type: 'checkbox', default: true, tag: 'ai' },
    { id: 'enable-sports', label: 'Hide Sports', type: 'checkbox', default: true, tag: 'ai' },
    { id: 'enable-politics', label: 'Hide Politics', type: 'checkbox', default: true, tag: 'ai' },
    { id: 'enable-gaming', label: 'Hide Gaming', type: 'checkbox', default: true, tag: 'ai' },
    { id: 'enable-food', label: 'Hide Food', type: 'checkbox', default: true, tag: 'ai' },
    { id: 'enable-business', label: 'Hide Business', type: 'checkbox', default: true, tag: 'ai' },
    { id: 'topic-threshold', label: 'Hide Threshold', type: 'number', default: 50, min: 5, max: 95, tag: 'topic' },
  ],
};
