export const facebookSettings = {
  General: [
    {
      id: 'fb-timeout',
      label: 'Facebook Timeout (seconds)',
      type: 'number',
      default: 0,
      min: 0,
      max: 300,
      tag: 'timeout',
    },
    {
      id: 'fb-pages-exempt',
      label: 'Pages Exempt',
      type: 'array',
      default: [],
      placeholder: 'e.g. /natgeo',
      tag: 'exemptions',
    },
    {
      id: 'fb-messengeroverlay-toggle',
      label: 'Hide Messenger Overlay',
      type: 'checkbox',
      default: true,
      tag: 'messages',
    },
    { id: 'fb-stories-toggle', label: 'Hide Stories', type: 'checkbox', default: true, tag: 'short' },
    { id: 'fb-reels-toggle', label: 'Hide Reels', type: 'checkbox', default: true, tag: 'short' },
  ],
  Navigation: [
    { id: 'fb-nav-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, tag: 'search' },
    { id: 'fb-nav-profile-toggle', label: 'Hide Profile Button', type: 'checkbox', default: true, tag: 'profile' },
    { id: 'fb-nav-home-toggle', label: 'Hide Home Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'fb-nav-video-toggle', label: 'Hide Video Button', type: 'checkbox', default: true, tag: 'main-nav' },
    {
      id: 'fb-nav-market-toggle',
      label: 'Hide Marketplace Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
    { id: 'fb-nav-groups-toggle', label: 'Hide Groups Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'fb-nav-gaming-toggle', label: 'Hide Gaming Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'fb-nav-menu-toggle', label: 'Hide Menu Button', type: 'checkbox', default: true, tag: 'main-nav' },
    {
      id: 'fb-nav-messages-toggle',
      label: 'Hide Messages Button',
      type: 'checkbox',
      default: true,
      tag: 'messages',
    },
    {
      id: 'fb-nav-notification-toggle',
      label: 'Hide Notification Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
  ],
  Posts: [
    { id: 'fb-posts-reacts-toggle', label: 'Hide Reacts', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'fb-posts-comments-toggle', label: 'Hide Comments', type: 'checkbox', default: true, tag: 'comments' },
    { id: 'fb-posts-shares-toggle', label: 'Hide Shares', type: 'checkbox', default: true, tag: 'post-actions' },
  ],
  Home: [
    { id: 'fb-home-posts-toggle', label: 'Hide Home Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'fb-home-shortcuts-toggle', label: 'Hide Shortcuts', type: 'checkbox', default: true, tag: 'other-nav' },
    {
      id: 'fb-home-suggestions-toggle',
      label: 'Hide Suggestions',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    {
      id: 'fb-home-contacts-toggle',
      label: 'Hide Contacts',
      type: 'checkbox',
      default: true,
      tag: 'messages',
    },
    {
      id: 'fb-home-groupchats-toggle',
      label: 'Hide Group Chats',
      type: 'checkbox',
      default: true,
      tag: 'messages',
    },
  ],
  Pages: [
    { id: 'fb-pages-posts-toggle', label: 'Hide Profile Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'fb-pages-shortcuts-toggle', label: 'Hide Shortcuts', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'fb-pages-intro-toggle', label: 'Hide Intro', type: 'checkbox', default: true, tag: 'info' },
    { id: 'fb-pages-photos-toggle', label: 'Hide Recent Photos', type: 'checkbox', default: true, tag: 'info' },
  ],
  Groups: [
    { id: 'fb-groups-posts-toggle', label: 'Hide Group Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'fb-groups-featured-toggle', label: 'Hide Featured Media', type: 'checkbox', default: true, tag: 'info' },
    { id: 'fb-groups-shortcuts-toggle', label: 'Hide Guides', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'fb-groups-about-toggle', label: 'Hide About', type: 'checkbox', default: true, tag: 'info' },
    { id: 'fb-groups-recentmedia-toggle', label: 'Hide Recent Media', type: 'checkbox', default: true, tag: 'info' },
    {
      id: 'fb-groups-recc-toggle',
      label: 'Hide Recommended Groups',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    {
      id: 'fb-groups-search-toggle',
      label: 'Hide Group Search',
      type: 'checkbox',
      default: true,
      tag: 'search',
    },
  ],
  Search: [
    { id: 'fb-search-posts-toggle', label: 'Hide Search Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'fb-search-filter-toggle', label: 'Hide Filter', type: 'checkbox', default: true, tag: 'filter' },
  ],
};
