export const facebookSettings = {
  General: [
    { id: 'fb-timeout', label: 'Facebook Timeout (seconds)', type: 'number', default: 0, min: 0, max: 300, rating: 4 },
    { id: 'fb-pages-exempt', label: 'Pages Exempt', type: 'array', default: [], placeholder: 'e.g. /natgeo' },
    {
      id: 'fb-messengeroverlay-toggle',
      label: 'Hide Messenger Overlay',
      type: 'checkbox',
      default: true,
      rating: 3,
      tag: 'messages',
    },
    { id: 'fb-stories-toggle', label: 'Hide Stories', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-reels-toggle', label: 'Hide Reels', type: 'checkbox', default: true, rating: 3 },
  ],
  Navigation: [
    { id: 'fb-nav-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, rating: 2, tag: 'search' },
    { id: 'fb-nav-profile-toggle', label: 'Hide Profile Button', type: 'checkbox', default: true, rating: 4 },
    { id: 'fb-nav-home-toggle', label: 'Hide Home Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-nav-video-toggle', label: 'Hide Video Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-nav-market-toggle', label: 'Hide Marketplace Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-nav-groups-toggle', label: 'Hide Groups Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-nav-gaming-toggle', label: 'Hide Gaming Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-nav-menu-toggle', label: 'Hide Menu Button', type: 'checkbox', default: true, rating: 2 },
    {
      id: 'fb-nav-messages-toggle',
      label: 'Hide Messages Button',
      type: 'checkbox',
      default: true,
      rating: 2,
      tag: 'messages',
    },
    { id: 'fb-nav-notification-toggle', label: 'Hide Notification Button', type: 'checkbox', default: true, rating: 2 },
  ],
  Posts: [
    { id: 'fb-posts-reacts-toggle', label: 'Hide Reacts', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-posts-comments-toggle', label: 'Hide Comments', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-posts-shares-toggle', label: 'Hide Shares', type: 'checkbox', default: true, rating: 3 },
  ],
  Home: [
    { id: 'fb-home-posts-toggle', label: 'Hide Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'fb-home-shortcuts-toggle', label: 'Hide Shortcuts', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-home-suggestions-toggle', label: 'Hide Suggestions', type: 'checkbox', default: true, rating: 3 },
    {
      id: 'fb-home-contacts-toggle',
      label: 'Hide Contacts',
      type: 'checkbox',
      default: true,
      rating: 3,
      tag: 'messages',
    },
    {
      id: 'fb-home-groupchats-toggle',
      label: 'Hide Group Chats',
      type: 'checkbox',
      default: true,
      rating: 3,
      tag: 'messages',
    },
  ],
  Pages: [
    { id: 'fb-pages-posts-toggle', label: 'Hide Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'fb-pages-shortcuts-toggle', label: 'Hide Shortcuts', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-pages-intro-toggle', label: 'Hide Intro', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-pages-photos-toggle', label: 'Hide Recent Photos', type: 'checkbox', default: true, rating: 3 },
  ],
  Groups: [
    { id: 'fb-groups-posts-toggle', label: 'Hide Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'fb-groups-featured-toggle', label: 'Hide Featured Media', type: 'checkbox', default: true, rating: 4 },
    { id: 'fb-groups-shortcuts-toggle', label: 'Hide Guides', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-groups-about-toggle', label: 'Hide About', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-groups-recentmedia-toggle', label: 'Hide Recent Media', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-groups-recc-toggle', label: 'Hide Recommended Groups', type: 'checkbox', default: true, rating: 3 },
    {
      id: 'fb-groups-search-toggle',
      label: 'Hide Group Search',
      type: 'checkbox',
      default: true,
      rating: 3,
      tag: 'search',
    },
  ],
  Search: [
    { id: 'fb-search-posts-toggle', label: 'Hide Search Feed', type: 'checkbox', default: false, rating: 5 },
    { id: 'fb-search-filter-toggle', label: 'Hide Filter', type: 'checkbox', default: true, rating: 3 },
  ],
};
