export const tagMap = {
  'on/off': 1,
  scroll: 1,
  limit: 1,
  content: 1,
  ai: 1,
  bias: 1,
  topic: 7, //7 until improvements
  exemptions: 1,
  short: 2,
  'main-nav': 2,
  messages: 3,
  postings: 3,
  'post-actions': 3,
  comments: 3,
  search: 3,
  suggestions: 3,
  news: 3,
  info: 4,
  'other-nav': 4,
  timeout: 4,
  chat: 4,
  filter: 4,
  profile: 5,
  grayscale: 5,
  nav: 6,
  'image/videos': 6,
  feed: 7,
};
