export const twitterSettings = {
  General: [
    { id: 'x-timeout', label: 'X Timeout (seconds)', type: 'number', default: 0, min: 0, max: 300, rating: 4 },
    { id: 'x-pages-exempt', label: 'Pages Exempt', type: 'array', default: [], placeholder: 'e.g. /NatGeo' },
  ],
  Navigation: [
    { id: 'x-nav-home-toggle', label: 'Hide Home Button', type: 'checkbox', default: true, rating: 2 },
    {
      id: 'x-nav-search-toggle',
      label: 'Hide Search Button',
      type: 'checkbox',
      default: true,
      rating: 2,
      tag: 'search',
    },
    { id: 'x-nav-notification-toggle', label: 'Hide Notification Button', type: 'checkbox', default: true, rating: 2 },
    {
      id: 'x-nav-messages-toggle',
      label: 'Hide Messages Button',
      type: 'checkbox',
      default: true,
      rating: 2,
      tag: 'messages',
    },
    { id: 'x-nav-grok-toggle', label: 'Hide Grok Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-list-toggle', label: 'Hide List Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-bookmark-toggle', label: 'Hide Bookmark Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-jobs-toggle', label: 'Hide Jobs Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-communities-toggle', label: 'Hide Communities Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-premium-toggle', label: 'Hide Premium Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-business-toggle', label: 'Hide Business Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-profile-toggle', label: 'Hide Profile Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-verifiedorgs-toggle', label: 'Hide Verified Orgs Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'x-nav-menu-toggle', label: 'Hide More Button', type: 'checkbox', default: true, rating: 4 },
  ],
  Posts: [
    { id: 'x-posts-stats-toggle', label: 'Hide Data', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-posts-reacts-toggle', label: 'Hide Reacts', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-posts-comments-toggle', label: 'Hide Comments', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-posts-shares-toggle', label: 'Hide Shares', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-posts-saves-toggle', label: 'Hide Save', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-posts-explain-toggle', label: 'Hide Explain Post', type: 'checkbox', default: true, rating: 3 },
  ],
  Home: [
    { id: 'x-home-posts-toggle', label: 'Hide Home Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'x-home-foryou-toggle', label: 'Hide For You Button', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-home-following-toggle', label: 'Hide Following Button', type: 'checkbox', default: false, rating: 5 },
    { id: 'x-home-trending-toggle', label: 'Hide Trending', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-home-recc-toggle', label: 'Hide Recommended', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-home-news-toggle', label: 'Hide News', type: 'checkbox', default: true, rating: 3 },
  ],
  Pages: [
    { id: 'x-pages-posts-toggle', label: 'Hide User Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'x-pages-replies-toggle', label: 'Hide Replies Tab', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-pages-articles-toggle', label: 'Hide Articles Tab', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-pages-highlights-toggle', label: 'Hide Highlights Tab', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-pages-media-toggle', label: 'Hide Media Tab', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-pages-affiliates-toggle', label: 'Hide Affiliates Tab', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-pages-suggestions-toggle', label: 'Hide Follow Suggestions', type: 'checkbox', default: true, rating: 3 },
  ],
  Explore: [
    { id: 'x-explore-feed-toggle', label: 'Hide Explore Feed', type: 'checkbox', default: true, rating: 5 },
    { id: 'x-explore-foryou-toggle', label: 'Hide For You', type: 'checkbox', default: true, rating: 4 },
    { id: 'x-explore-news-toggle', label: 'Hide News', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-explore-trending-toggle', label: 'Hide Trending', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-explore-sports-toggle', label: 'Hide Sports', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-explore-entertainment-toggle', label: 'Hide Entertainment', type: 'checkbox', default: true, rating: 3 },
  ],
  Search: [
    { id: 'x-search-feed-toggle', label: 'Hide Search Feed', type: 'checkbox', default: true, rating: 5 },
    { id: 'x-search-top-toggle', label: 'Hide Top', type: 'checkbox', default: true, rating: 4 },
    { id: 'x-search-latest-toggle', label: 'Hide Latest', type: 'checkbox', default: true, rating: 4 },
    { id: 'x-search-people-toggle', label: 'Hide People', type: 'checkbox', default: true, rating: 4 },
    { id: 'x-search-lists-toggle', label: 'Hide Lists', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-search-news-toggle', label: 'Hide News', type: 'checkbox', default: true, rating: 3 },
    { id: 'x-search-filter-toggle', label: 'Hide Filter', type: 'checkbox', default: true, rating: 3 },
  ],
};
