export const twitterSettings = {
  General: [
    { id: 'x-timeout', label: 'X Timeout (seconds)', type: 'number', default: 0, min: 0, max: 300, tag: 'timeout' },
    {
      id: 'x-pages-exempt',
      label: 'Pages Exempt',
      type: 'array',
      default: [],
      placeholder: 'e.g. /NatGeo',
      tag: 'exemptions',
    },
    {
      id: 'x-followsuggestions-toggle',
      label: 'Follow Suggestions',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
  ],
  Navigation: [
    { id: 'x-nav-home-toggle', label: 'Hide Home Button', type: 'checkbox', default: true, tag: 'main-nav' },
    {
      id: 'x-nav-search-toggle',
      label: 'Hide Search Button',
      type: 'checkbox',
      default: true,
      tag: 'search',
    },
    {
      id: 'x-nav-notification-toggle',
      label: 'Hide Notification Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
    {
      id: 'x-nav-follows-toggle',
      label: 'Hide Follows Button',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    {
      id: 'x-nav-messages-toggle',
      label: 'Hide Messages Button',
      type: 'checkbox',
      default: true,
      tag: 'messages',
    },
    { id: 'x-nav-grok-toggle', label: 'Hide Grok Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'x-nav-list-toggle', label: 'Hide List Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'x-nav-bookmark-toggle', label: 'Hide Bookmark Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'x-nav-studio-toggle', label: 'Hide Creator Studio Button', type: 'checkbox', default: true, tag: 'posting' },
    {
      id: 'x-nav-communities-toggle',
      label: 'Hide Communities Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
    { id: 'x-nav-premium-toggle', label: 'Hide Premium Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'x-nav-business-toggle', label: 'Hide Business Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'x-nav-profile-toggle', label: 'Hide Profile Button', type: 'checkbox', default: true, tag: 'main-nav' },
    {
      id: 'x-nav-verifiedorgs-toggle',
      label: 'Hide Verified Orgs Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
    { id: 'x-nav-menu-toggle', label: 'Hide More Button', type: 'checkbox', default: true, tag: 'profile' },
  ],
  Posts: [
    { id: 'x-posts-stats-toggle', label: 'Hide Data', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'x-posts-reacts-toggle', label: 'Hide Reacts', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'x-posts-comments-toggle', label: 'Hide Comments', type: 'checkbox', default: true, tag: 'comments' },
    { id: 'x-posts-shares-toggle', label: 'Hide Shares', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'x-posts-saves-toggle', label: 'Hide Save', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'x-posts-explain-toggle', label: 'Hide Explain Post', type: 'checkbox', default: true, tag: 'post-actions' },
  ],
  Home: [
    { id: 'x-home-posts-toggle', label: 'Hide Home Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'x-home-foryou-toggle', label: 'Hide For You Button', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-home-following-toggle', label: 'Hide Following Button', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'x-home-trending-toggle', label: 'Hide Trending', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-home-recc-toggle', label: 'Hide Recommended', type: 'checkbox', default: true, tag: 'suggestions' },
    { id: 'x-home-news-toggle', label: 'Hide News', type: 'checkbox', default: true, tag: 'news' },
  ],
  Pages: [
    { id: 'x-pages-posts-toggle', label: 'Hide Profile Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'x-pages-replies-toggle', label: 'Hide Replies Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-pages-articles-toggle', label: 'Hide Articles Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    {
      id: 'x-pages-highlights-toggle',
      label: 'Hide Highlights Tab',
      type: 'checkbox',
      default: true,
      tag: 'other-nav',
    },
    { id: 'x-pages-media-toggle', label: 'Hide Media Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    {
      id: 'x-pages-affiliates-toggle',
      label: 'Hide Affiliates Tab',
      type: 'checkbox',
      default: true,
      tag: 'other-nav',
    },
    {
      id: 'x-pages-suggestions-toggle',
      label: 'Hide Follow Suggestions',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
  ],
  Explore: [
    { id: 'x-explore-feed-toggle', label: 'Hide Explore Feed', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'x-explore-foryou-toggle', label: 'Hide For You', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'x-explore-news-toggle', label: 'Hide News', type: 'checkbox', default: true, tag: 'news' },
    { id: 'x-explore-trending-toggle', label: 'Hide Trending', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-explore-sports-toggle', label: 'Hide Sports', type: 'checkbox', default: true, tag: 'other-nav' },
    {
      id: 'x-explore-entertainment-toggle',
      label: 'Hide Entertainment',
      type: 'checkbox',
      default: true,
      tag: 'other-nav',
    },
  ],
  Search: [
    { id: 'x-search-feed-toggle', label: 'Hide Search Feed', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'x-search-top-toggle', label: 'Hide Top', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'x-search-latest-toggle', label: 'Hide Latest', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-search-people-toggle', label: 'Hide People', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-search-lists-toggle', label: 'Hide Lists', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'x-search-news-toggle', label: 'Hide News', type: 'checkbox', default: true, tag: 'news' },
    { id: 'x-search-filter-toggle', label: 'Hide Filter', type: 'checkbox', default: true, tag: 'filter' },
    {
      id: 'x-search-communities-toggle',
      label: 'Hide Explore Communities',
      type: 'checkbox',
      default: true,
      tag: 'other-nav',
    },
  ],
};
