export const twitchSettings = {
  General: [
    { id: 'tw-timeout', label: 'X Timeout (seconds)', type: 'number', default: 0, min: 0, max: 300, tag: 'timeout' },
    {
      id: 'tw-pages-exempt',
      label: 'Pages Exempt',
      type: 'array',
      default: [],
      placeholder: 'e.g. /k3soju',
      tag: 'exemptions',
    },
  ],
  Navigation: [
    { id: 'tw-following-toggle', label: 'Hide Following Button', type: 'checkbox', default: true, tag: 'profile' },
    { id: 'tw-browse-toggle', label: 'Hide Browse Button', type: 'checkbox', default: true, tag: 'search' },
    { id: 'tw-more-toggle', label: 'Hide More Options Button', type: 'checkbox', default: true, tag: 'nav' },
    { id: 'tw-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, tag: 'search' },
    { id: 'tw-news-toggle', label: 'Hide News From Prime', type: 'checkbox', default: true, tag: 'news' },
    {
      id: 'tw-notifications-toggle',
      label: 'Hide Notification Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
    { id: 'tw-whispers-toggle', label: 'Hide Whisper Button', type: 'checkbox', default: true, tag: 'messages' },
    { id: 'tw-getbits-toggle', label: 'Hide Get Bits Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'tw-adfree-toggle', label: 'Hide Twitch Turbo Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'tw-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, tag: 'search' },
  ],
  Posts: [
    { id: 'tw-livechat-toggle', label: 'Hide Live Chat', type: 'checkbox', default: true, tag: 'suggestions' },
    { id: 'tw-description-toggle', label: 'Hide Descriptions', type: 'checkbox', default: true, tag: 'suggestions' },
    {
      id: 'tw-commenting-toggle',
      label: 'Hide Send a Message Box',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    { id: 'tw-tags-toggle', label: 'Hide Stream Tags', type: 'checkbox', default: true, tag: 'suggestions' },
    { id: 'tw-share-toggle', label: 'Hide Share Button', type: 'checkbox', default: true, tag: 'suggestions' },
  ],
  Home: [
    { id: 'tw-followed-toggle', label: 'Hide Followed Channel List', type: 'checkbox', default: true, tag: 'profile' },
    {
      id: 'tw-sidebarsuggestions-toggle',
      label: 'Hide Sidebar Recommendations',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    {
      id: 'tw-feedsuggestions-toggle',
      label: 'Limit Recommendations in Feed',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    { id: 'tw-carousel-toggle', label: 'Hide Carousel', type: 'checkbox', default: true, tag: 'suggestions' },
  ],
  Pages: [
    { id: 'tw-livechat-toggle', label: 'Hide Live Chat', type: 'checkbox', default: true, tag: 'suggestions' },
    { id: 'tw-description-toggle', label: 'Hide Descriptions', type: 'checkbox', default: true, tag: 'suggestions' },
    {
      id: 'tw-commenting-toggle',
      label: 'Hide Send a Message Box',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    { id: 'tw-tags-toggle', label: 'Hide Stream Tags', type: 'checkbox', default: true, tag: 'suggestions' },
    { id: 'tw-share-toggle', label: 'Hide Share Button', type: 'checkbox', default: true, tag: 'suggestions' },
  ],
  Search: [],
};
