export const twitchSettings = {
  General: [
    { id: 'tw-timeout', label: 'X Timeout (seconds)', type: 'number', default: 0, min: 0, max: 300, tag: 'timeout' },
    {
      id: 'tw-pages-exempt',
      label: 'Pages Exempt',
      type: 'array',
      default: [],
      placeholder: 'e.g. /k3soju',
      tag: 'exemptions',
    },
  ],
  Navigation: [
    { id: 'tw-nav-following-toggle', label: 'Hide Following Button', type: 'checkbox', default: true, tag: 'profile' },
    {
      id: 'tw-nav-sidebarsuggestions-toggle',
      label: 'Hide Sidebar Recommendations',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    { id: 'tw-nav-browse-toggle', label: 'Hide Browse Button', type: 'checkbox', default: true, tag: 'search' },
    { id: 'tw-nav-more-toggle', label: 'Hide More Options Button', type: 'checkbox', default: true, tag: 'nav' },
    { id: 'tw-nav-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, tag: 'search' },
    { id: 'tw-nav-news-toggle', label: 'Hide Prime News', type: 'checkbox', default: true, tag: 'news' },
    {
      id: 'tw-nav-notifications-toggle',
      label: 'Hide Notification Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
    { id: 'tw-nav-whispers-toggle', label: 'Hide Whisper Button', type: 'checkbox', default: true, tag: 'messages' },
    { id: 'tw-nav-getbits-toggle', label: 'Hide Get Bits Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'tw-nav-adfree-toggle', label: 'Hide Twitch Turbo Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'tw-nav-profile-toggle', label: 'Hide Profile', type: 'checkbox', default: true, tag: 'profile' },
  ],
  Posts: [
    { id: 'tw-posts-livechat-toggle', label: 'Hide Live Chat', type: 'checkbox', default: true, tag: 'chat' },
    {
      id: 'tw-posts-description-toggle',
      label: 'Hide Descriptions',
      type: 'checkbox',
      default: true,
      tag: 'description',
    },
    { id: 'tw-posts-panels-toggle', label: 'Hide Panels', type: 'checkbox', default: true, tag: 'info' },
    {
      id: 'tw-posts-commenting-toggle',
      label: 'Hide Message Box',
      type: 'checkbox',
      default: true,
      tag: 'messages',
    },
    { id: 'tw-posts-tags-toggle', label: 'Hide Stream Tags', type: 'checkbox', default: true, tag: 'filter' },
    { id: 'tw-posts-share-toggle', label: 'Hide Share Button', type: 'checkbox', default: true, tag: 'post-actions' },
  ],
  Home: [
    {
      id: 'tw-home-feed-toggle',
      label: 'Hide Home Feed',
      type: 'checkbox',
      default: true,
      tag: 'feed',
    },
    { id: 'tw-home-carousel-toggle', label: 'Hide Carousel', type: 'checkbox', default: true, tag: 'suggestions' },
  ],
  Pages: [
    { id: 'tw-pages-feed-toggle', label: 'Hide Pages Feed', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'tw-pages-live-toggle', label: 'Hide Header', type: 'checkbox', default: true, tag: 'chat' },
    { id: 'tw-pages-home-toggle', label: 'Hide Home Tab', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'tw-pages-about-toggle', label: 'Hide About Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'tw-pages-schedule-toggle', label: 'Hide Schedule Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'tw-pages-videos-toggle', label: 'Hide Videos Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'tw-pages-chat-toggle', label: 'Hide Chat Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'tw-pages-sub-toggle', label: 'Hide Sub Buttons', type: 'checkbox', default: true, tag: 'info' },
  ],
  Search: [
    { id: 'tw-search-feed-toggle', label: 'Hide Browse Feed', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'tw-search-genre-toggle', label: 'Hide Browse Genres', type: 'checkbox', default: true, tag: 'search' },
    { id: 'tw-search-filters-toggle', label: 'Hide Browse Filters', type: 'checkbox', default: true, tag: 'search' },
  ],
};
