export const youtubeSettings = {
  General: [
    { id: 'yt-timeout', label: 'YT Timeout (seconds)', type: 'number', default: 0, min: 0, max: 300, tag: 'timeout' },
    {
      id: 'yt-pages-exempt',
      label: 'Pages Exempt',
      type: 'array',
      default: [],
      placeholder: 'e.g. /@NatGeo',
      tag: 'exemptions',
    },
    { id: 'yt-shorts-toggle', label: 'Hide Shorts', type: 'checkbox', default: true, tag: 'short' },
  ],
  Navigation: [
    { id: 'yt-nav-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, tag: 'search' },
    { id: 'yt-nav-home-toggle', label: 'Hide Home Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'yt-nav-profile-toggle', label: 'Hide Profile', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'yt-nav-you-toggle', label: 'Hide Your Stuff', type: 'checkbox', default: true, tag: 'profile' },
    { id: 'yt-nav-subscriptions-toggle', label: 'Hide Subscriptions', type: 'checkbox', default: true, tag: 'profile' },
    { id: 'yt-nav-explore-toggle', label: 'Hide Explore Button', type: 'checkbox', default: true, tag: 'main-nav' },
    { id: 'yt-nav-morefrom-toggle', label: 'Hide More From YouTube', type: 'checkbox', default: true, tag: 'main-nav' },
    {
      id: 'yt-nav-notification-toggle',
      label: 'Hide Notification Button',
      type: 'checkbox',
      default: true,
      tag: 'main-nav',
    },
  ],
  Posts: [
    {
      id: 'yt-posts-description-toggle',
      label: 'Hide Descriptions',
      type: 'checkbox',
      default: false,
      tag: 'description',
    },
    {
      id: 'yt-posts-suggestions-toggle',
      label: 'Hide Suggestions',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    { id: 'yt-posts-mixes-toggle', label: 'Hide Music Mixes', type: 'checkbox', default: true, tag: 'suggestions' },
    { id: 'yt-posts-reacts-toggle', label: 'Hide Reacts', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'yt-posts-comments-toggle', label: 'Hide Comments', type: 'checkbox', default: true, tag: 'comments' },
    { id: 'yt-posts-livechat-toggle', label: 'Hide Stream Chat', type: 'checkbox', default: true, tag: 'chat' },
    { id: 'yt-posts-shares-toggle', label: 'Hide Shares', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'yt-posts-saves-toggle', label: 'Hide Save', type: 'checkbox', default: true, tag: 'post-actions' },
    {
      id: 'yt-posts-download-toggle',
      label: 'Hide Download Button',
      type: 'checkbox',
      default: true,
      tag: 'post-actions',
    },
    { id: 'yt-posts-clip-toggle', label: 'Hide Clip Button', type: 'checkbox', default: true, tag: 'post-actions' },
    { id: 'yt-posts-askai-toggle', label: 'Hide Ask AI Button', type: 'checkbox', default: true, tag: 'post-actions' },
  ],
  Home: [
    { id: 'yt-home-posts-toggle', label: 'Hide Posts', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'yt-home-genres-toggle', label: 'Hide Genres', type: 'checkbox', default: true, tag: 'suggestions' },
    {
      id: 'yt-home-featured-toggle',
      label: 'Hide YouTube Featured',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
    { id: 'yt-home-playables-toggle', label: 'Hide Playables', type: 'checkbox', default: true, tag: 'short' },
    { id: 'yt-home-breakingnews-toggle', label: 'Hide Breaking News', type: 'checkbox', default: true, tag: 'news' },
  ],
  Pages: [
    { id: 'yt-pages-feed-toggle', label: 'Hide Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'yt-pages-home-toggle', label: 'Hide Home', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'yt-pages-videos-toggle', label: 'Hide Videos Tab', type: 'checkbox', default: true, tag: 'feed' },
    { id: 'yt-pages-live-toggle', label: 'Hide Live Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'yt-pages-playlists-toggle', label: 'Hide Playlists Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'yt-pages-posts-toggle', label: 'Hide Posts Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'yt-pages-store-toggle', label: 'Hide Store Tab', type: 'checkbox', default: true, tag: 'other-nav' },
    { id: 'yt-pages-podcasts-toggle', label: 'Hide Podcasts Tab', type: 'checkbox', default: true, tag: 'other-nav' },
  ],
  Search: [
    { id: 'yt-search-feed-toggle', label: 'Hide Search Feed', type: 'checkbox', default: false, tag: 'feed' },
    { id: 'yt-search-filter-toggle', label: 'Hide Filter Option', type: 'checkbox', default: false, tag: 'filter' },
    {
      id: 'yt-search-secondary-toggle',
      label: 'Hide Secondary Search Results',
      type: 'checkbox',
      default: true,
      tag: 'suggestions',
    },
  ],
};
